---

AWSTemplateFormatVersion: '2010-09-09'

Description: Create a IAM Role for EC2 read-only access

Parameters:
  ManagedPolicyARN:
    Description: Specify Policy ARN to associate with IAM Role
    Type: String
    Default: arn:aws:iam::aws:policy/ReadOnlyAccess

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        -
          Ref: 'ManagedPolicyARN'
      Path: "/"
    

  EC2Profile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: "/"
      Roles:
        -
          Ref: InstanceRole

Outputs:
  InstanceProfile:
    Description: EC2 Profile
    Value: !Ref EC2Profile
    Export:
      Name: EC2Profile