---
AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Main VPC for Module 1.4

Parameters:
  VPCCIDR:
    Description: 'Network CIDR'
    Type: String
    Default: 10.0.0.0/20

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: Module-1_4-VPC

Outputs:
  VPC:
    Description: Reference to created VPC
    Value: !Ref VPC
    